name: Debug Connectivity and Run Hello World on Prod Server

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Test DNS Resolution
        run: |
          echo "Testing DNS resolution using the public resolver (8.8.8.8)..."
          nslookup ${{ secrets.DEV_SERVER_HOST }} 8.8.8.8 || echo "DNS resolution failed"
          
      - name: Test Ping Connectivity
        run: |
          echo "Testing connectivity with ping..."
          ping -c 4 ${{ secrets.DEV_SERVER_HOST }} || echo "Ping failed"
          
      - name: Test SSH Port Accessibility
        run: |
          echo "Testing SSH port accessibility..."
          nc -zv ${{ secrets.DEV_SERVER_HOST }} 22 || echo "Port 22 is not accessible"

  run-on-server:
    runs-on: ubuntu-latest
    needs: debug  # Ensure the debug job completes before this one

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH and Run Hello World on Prod Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "192.168.1.113"
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            echo "Hello, World!" > ~/hello-world.txt
            cat ~/hello-world.txt
