name: Deploy Docker Container to Server

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from Docker Hub (or any other registry)
        run: |
          docker pull your-dockerhub-username/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes successfully before deploying

    steps:
      - name: SSH to the server and deploy the Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "65.108.37.107"
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the Docker image from Docker Hub
            docker pull your-dockerhub-username/your-image-name:latest
            
            # Stop any running container (if any)
            docker stop node-docker-app || true
            docker rm node-docker-app || true
            
            # Run the new container
            docker run -d --name node-docker-app -p 3000:3000 your-dockerhub-username/your-image-name:latest
