name: Hello World on Prod Server

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Test DNS Resolution with Public Resolver
        run: |
          echo "Testing DNS resolution using a public resolver..."
          nslookup ${{ secrets.PROD_SERVER_HOST }} 8.8.8.8 || echo "DNS resolution failed"

      - name: Check Connectivity with Ping
        run: |
          echo "Testing connectivity with ping..."
          ping -c 4 ${{ secrets.PROD_SERVER_HOST }} || echo "Ping failed"

      - name: Check SSH Port Accessibility
        run: |
          echo "Testing SSH port accessibility..."
          nc -zv ${{ secrets.PROD_SERVER_HOST }} 22 || echo "Port 22 is not accessible"

  run-on-server:
    runs-on: ubuntu-latest
    needs: debug

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH and Run Hello World on Prod Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Hello, World!" > ~/hello-world.txt
            cat ~/hello-world.txt
