name: Hello World on Prod Server

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Testing DNS Resolution and Connectivity
        run: |
          echo "Testing DNS resolution and connectivity to the server"
          echo "Checking DNS resolution..."
          nslookup ${{ secrets.PROD_SERVER_HOST }} || echo "DNS resolution failed"
          echo "Checking connectivity with ping..."
          ping -c 4 ${{ secrets.PROD_SERVER_HOST }} || echo "Ping failed"
          echo "Checking if port 22 is accessible..."
          nc -zv ${{ secrets.PROD_SERVER_HOST }} 22 || echo "Port 22 is not accessible"

  run-on-server:
    runs-on: ubuntu-latest
    needs: debug  # Ensure debug job completes before this one

    steps:
      # Step 1: Checkout the repository (optional for this task)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: SSH into the server and run a command
      - name: SSH and Run Hello World on Prod Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Hello, World!" > ~/hello-world.txt
            cat ~/hello-world.txt
