name: Self-Hosted Runner Test

on:
  push:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "Hello, self-hosted runner!"
