name: Debug Connectivity to Prod Server

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Test DNS Resolution
        run: |
          echo "Testing DNS resolution using the public resolver (8.8.8.8)..."
          nslookup ${{ secrets.PROD_SERVER_HOST }} 8.8.8.8 || echo "DNS resolution failed"
          
      - name: Test Ping Connectivity
        run: |
          echo "Testing connectivity with ping..."
          ping -c 4 ${{ secrets.PROD_SERVER_HOST }} || echo "Ping failed"
          
      - name: Test SSH Port Accessibility
        run: |
          echo "Testing SSH port accessibility..."
          nc -zv ${{ secrets.PROD_SERVER_HOST }} 22 || echo "Port 22 is not accessible"
